---
title: "Test species-area / species-environment curves"
author: "Florian Hartig"
date: "14 Jan 2016"
output: html_document
---

```{r}
library(PhyloSim)
set.seed(123)
```


# Creating species dependent on the environent

```{r, cache=T}
size = 100

par <- createCompletePar(x = size, y = size, dispersal = 1, runs = 2500, density = 0, environment = 1, specRate = 4, fission = 0)

system.time(simu <- runSimulation(par))

plotSpatialPhylo(simu, plot = "both")

plots = localPlots(simu, size = 2, n = 200, nested = F)

```

### Analysis of SACs 

```{r}
nspc = rep(NA, 100)
nenv = rep(NA, 100)

for(i in 1:100){
  species = unlist(plots$subPlots[1:i])
  env = unlist(plots$envPlots[1:i])
  nspc[i] = length(unique(species))
  nenv[i] = sum(seq(0,1,0.01) %in% round(env, digits = 2) )
}

par(mfrow = c(1,2))
plot(1:100, nspc, main = "Species accumulation curve")
plot(nenv, nspc, main = "Species - environment curve")
```


### Analysis of beta diversity

```{r}
plots = localPlots(simu, size = 5, n = 200, nested = F)

# Create dataset 
out <- data.frame(turnover = rep(NA, 199), dist = rep(NA, 199), env = rep(NA), 199)
for(i in 1:199){
  p1 = plots$subPlots[i]
  p2 = plots$subPlots[i+1]
  e1 = plots$envPlots[i]
  e2 = plots$envPlots[i+1]
  
  out$turnover[i] = sum(! unique(unlist(p1)) %in% unique(unlist(p2)))
  out$env[i] = abs(mean(unlist(e1)) - mean(unlist(e2)))
  out$dist[i] = sqrt(sum((plots$locations[i, ] - plots$locations[i+1, ])^2))
}

par(mfrow = c(1,2))
plot(turnover ~ dist, data = out, main = "Beta ~ dist")
plot(turnover ~ env, data = out, main = "Beta ~ env")

summary(lm(turnover ~ dist + env, data = out))

```


# Creating species not dependent on the environent (neutral)

```{r, cache=T}

par <- createCompletePar(x = size, y = size, dispersal = 1, runs = 2500, density = 0, environment = 0, specRate = 4, fission = 0)

system.time(simu <- runSimulation(par))

plotSpatialPhylo(simu, plot = "both")

```


### Analysis of SACs 

```{r}
nspc = rep(NA, 100)
nenv = rep(NA, 100)

for(i in 1:100){
  species = unlist(plots$subPlots[1:i])
  env = unlist(plots$envPlots[1:i])
  nspc[i] = length(unique(species))
  nenv[i] = sum(seq(0,1,0.01) %in% round(env, digits = 2) )
}

par(mfrow = c(1,2))
plot(1:100, nspc, main = "Species accumulation curve")
plot(nenv, nspc, main = "Species - environment curve")
```


### Analysis of beta diversity

```{r}
plots = localPlots(simu, size = 5, n = 200, nested = F)

# Create dataset 
out <- data.frame(turnover = rep(NA, 199), dist = rep(NA, 199), env = rep(NA), 199)
for(i in 1:199){
  p1 = plots$subPlots[i]
  p2 = plots$subPlots[i+1]
  e1 = plots$envPlots[i]
  e2 = plots$envPlots[i+1]
  
  out$turnover[i] = sum(! unique(unlist(p1)) %in% unique(unlist(p2)))
  out$env[i] = abs(mean(unlist(e1)) - mean(unlist(e2)))
  out$dist[i] = sqrt(sum((plots$locations[i, ] - plots$locations[i+1, ])^2))
}

par(mfrow = c(1,2))
plot(turnover ~ dist, data = out, main = "Beta ~ dist")
plot(turnover ~ env, data = out, main = "Beta ~ env")

summary(lm(turnover ~ dist + env, data = out))

```


