#' @title Plot Phylogenetic Dispersion
#' @description Plotting function for the results of \code{\link{calculatePhylogeneticDispersion}}. It is used to compare different scenarios.
#' @param pvalues List of p-values as generated by \code{\link{calculatePhylogeneticDispersion}}.
#' @param positions List, determines where the plots should be placed and how they should be labeled (see Details). The list need to have the entries x, y, xname and yname.
#' @param title String, determines the title of the plot
#' @param which.result Integer, determines which result should be used. By default (NULL), the last result is used.
#' @param xmax Float, determines the plot limit (max) of the x axis.
#' @param ymax Float, determines the plot limit (max) of the y axis.
#' @param xmin Float, determines the plot limit (min) of the x axis.
#' @param ymin Float, determines the plot limit (min) of the y axis.
#' @param means Integer, determines the number of results which are used to average the results.
#' @details In every subplot the x-axis represents the size of the subplots used in the null models. Hence, it is recommended to use a vector of plot sizes in your \code{\link{calculatePhylogeneticDispersion}} setup. \cr\cr The which.result argument here is used on the input list of p-values. Hence, which.result = 1 plots the first list slice of the input here. This is not necessarily the first time step of of your parameter settings in \code{\link{runSimulationBatch}}. \cr\cr For an further explanation please see the Examples section. 
#' @example /inst/examples/plotPhylogeneticDispersion-help.R
#' @export
#' 
plotPhylogeneticDispersion <- function(pvalues, positions=NULL, title = "P-values", which.result = NULL, xmax = 5.5, ymax = 2.5, xmin = -0.2, ymin = 0.5, means=1){
  
  if(means > length(pvalues)){
    stop ("Error. Argument 'means' too large for dataset.")
  }
  
  if (is.null(positions)){
    stop("Error. No positions defined.")
  }  
  
  
  xcol <- length(positions$x)
  ycol <- length(positions$y)
  lengths = as.numeric(names(pvalues[[1]][[1]]))
  nlengths = length(lengths)
  lRange <- max(lengths) - min(lengths)
  
  MeanMatZ<-array(NA, dim=c(nlengths,length(pvalues[[1]]), means))
  MeanMatZLow<-array(NA, dim=c(nlengths,length(pvalues[[1]]), means))
  MeanMatZUp<-array(NA, dim=c(nlengths,length(pvalues[[1]]), means))
  
   for(m in 1:means){
     
  if(m == 1){
   if(is.null(which.result)){
     pvaluesT<-pvalues[[length(pvalues)]]
     } else{
       pvaluesT <- pvalues[[which.result]]
     }
     }
    
  if(m != 1){
    if(is.null(which.result)) {
      pvaluesT<-pvalues[[length(pvalues)-(m-1)]]
      } else{
        pvaluesT <- pvalues[[which.result-(m-1)]]
      }
      }
    
  z <- matrix(nrow = nlengths, ncol = length(pvaluesT), 
              dimnames = list(names(pvaluesT[[1]]), names(pvaluesT)))
  zCILOW <- z
  zCIUP <- z
  for (i in 1:length(pvaluesT)){
    z[,i] <- sapply(pvaluesT[[i]], median, na.rm = T)
    zCILOW[,i] <- sapply(pvaluesT[[i]], function(x)quantile(x,0.25, na.rm = T))   
    zCIUP[,i] <- sapply(pvaluesT[[i]], function(x)quantile(x,0.75, na.rm = T))
  }
  
  MeanMatZ[,,m]<-z
  MeanMatZLow[,,m]<-zCILOW
  MeanMatZUp[,,m]<-zCIUP
   }
  
  for(i in 1:nlengths){
    for(k in 1:length(pvaluesT)){
      z[i,k]<-mean(MeanMatZ[i,k,])
      zCILOW[i,k]<-mean(MeanMatZLow[i,k,])
      zCIUP[i,k]<-mean(MeanMatZUp[i,k,])
    }
  }
  
  ColPalet <- colorRampPalette(c("turquoise4", "white", "palevioletred"))
  Cols <- ColPalet(100)
  index <- seq(0,1,0.01)
  oldpar<-par()
  
  par(mar=c(0, 3, 0, 0), xpd=TRUE)
  shape::emptyplot(xlim=c(0, xmax), ylim=c(0.5,ymax), asp=1, frame.plot = FALSE)
  text(x = median(positions$x/2), y = 1.5*ycol/2 ,  labels= title, cex=1.3)
  
  for(i in 1:length(positions$y)){
    for(j in 1:length(positions$x)){
      
      x <- positions$x[j] / 2
      fitn = positions$zname[j]
      
      disp = positions$yname[i]
      y <- positions$y[i] / 2
      
      k <- length(positions$x)*(i-1) + j
      
      mpv <- mean(z[,k])
      shape::filledrectangle(wx = 0.3 ,wy = 0.3, col = Cols[which.max(index[index <= mpv])],
              mid = c(x, y), angle = 0, lcol = "darkgrey")
      
      xval <- (lengths - min(lengths)) / lRange *0.3 -0.15
      yval <- z[,k] * 0.3 - 0.15
      yUP <- zCIUP[,k] * 0.3 - 0.15 
      yLOW <- zCILOW[,k] * 0.3 - 0.15
      
      polygon(c(x+xval, rev(x+xval)), c(y+yUP, rev(y+yLOW)), col = "#99999940", border = NA)
      lines(x+xval, y+yval)
      lines(c(x-0.15,x-0.13) , c(y , y ))
      lines(c(x+0.13,x+0.15) , c(y , y ))
    }
  }
  
  text(x = -0.26*min(positions$x), y = positions$y/2, labels = positions$yname , pos = 4) 
  text(x = positions$x/2, y = 1.2*ycol/2, labels =  positions$zname ) 
  text(x = positions$x/2, y = 0,  labels= positions$xname)
  
  barx <- max(positions$x)/2+ min(positions$x)/2
  bary <- mean(positions$y)/2
  barl <- 0.3
  
  fields::colorbar.plot(x = barx, y = bary, strip=seq(0,1,0.001), col=Cols, 
                        strip.length = barl, horizontal = F, strip.width = 0.04)
  text(x = barx+0.1 , y = bary + 1.8* barl, labels = "overdispersed" , pos = 4) 
  text(x = barx+0.1 , y = bary, labels = "neutral" , pos = 4) 
  text(x = barx+0.1 , y = bary - 1.8* barl, labels = "underdispersed \n(clustered)", pos = 4) 

  par(mar=oldpar$mar, xpd=oldpar$xpd)
}


