\documentclass{article}

\author{Florian Hartig}
\title{Introduction to the phylosim package \\ Simulating species community assembly processes}

\begin{document}
\SweaveOpts{concordance=TRUE}
\maketitle


\section{Introduction}
The question whether or to which degree on can infer community assembly processes from their resulting spatial and phylogenetic patterns is of central importance in ecology. It is these processes that create and maintain local assemblages.\\
Currently there are many different explanations as to how species communities are shaped based on the emerging spatial or phylogenetic patterns. 
The phylosim package represents an expansion of previous models by combining these informations. This may yield pattern combinations that are much more distinct than phylogenetic or spatial patterns alone.\\
The simulation includes dispersal limitation, environmental preferences and local competition, whereas the outcome consists of phylogenetic and spatial patterns.\\
Among the central model the package comprises a set of functions to illustrate and analyze the results.



\section{Background}



\section{Basic functionality}


\subsection{Loading the package}

Loading the package via

<<>>=
library(PhylGeo)
@


\subsection{Run the model}
Running the model consists of two consecutive steps. First a list of parameters is generated based on the users settings.\\
In the following example an area of 50*50 cells provides the basis for two simulations with 500 or 1000 generations respectively. \\
<<>>=
par <- createCompletePar(x = 50, y = 50, dispersal = 0 , runs = c(500,1000), density = 1, environment = 0.5, specRate = 1)
@

For further explanation and more settings see:
<<>>=
?createCompletePar
@

The list of parameters is now being used to exectute the simulation:

<<>>=
simu <- runSimulation(par)
@


The output is saved as a list. The first two list slices contain the results of the two simulations, whereas the last list slice contains the parameter settings.

<<>>=
str(simu)
@


\subsection{Plots and summary statistics}
The phylosim package contaions  multiple functions to visualize the results of the simulation.
The plotSpatialPhylo function can plot the resulting landscape, phylogeny and the evolved traits.

<<fig=TRUE>>=
plotSpatialPhylo(simu, plot = "both", plotTraits = T, time=1)
@

To analyze the results the package contains functions to calculate and visualize the rank-abundace curve (RAC) and species-area curve (SAC) for the output.

<<fig=TRUE>>=
par(mfrow = c(2,2),mar=c(1.5, 3, 3, 0.5))
rac(simu[[1]]$specMat)
sac(simu[[1]]$specMat)
rac(simu[[2]]$specMat)
sac(simu[[2]]$specMat)
@


Further it is possible to calculate the species richness of the results.

<<>>=

specRich(simu[[1]]$specMat)
specRich(simu[[2]]$specMat)
@


\section{Other models}

\subsection{Neutral model}

This implements a purely neutral model in R ... only for test and teaching purposes, far too slow to be useful in practice

<<fig=TRUE>>=

# Run the model
metaCom <- NeutralMod(dim=50, specRate=2, seed=1500, runs=1500)
# Visualize the grid
image(metaCom)
# Calculate the species area-relation
rac(metaCom, plot="line")

@



<<>>=



library(PhylGeo)

par <- createCompletePar(x = 50, y = 50, dispersal = 1, runs = c(500,1000), density = 1, environment = 0.5, specRate = 1)

system.time(simu <- runSimulation(par))

plotSpatialPhylo(simu, plot = "both")

plotTraitDistribution(simu)


@




\end{document}