---
title: "Plots"
author: "Stefan"
date: "4. Dezember 2015"
output: html_document
---
In this document all the plots are described.

You'll find the following sections:
- 8. Null Models
- 9. Species Richness
- 10. Gamma Statistics
- 11. Colless' Imbalance
- 12. SAC
- 13. RAC

To store all the plots we create two subdirectories called 'plot100' and 'plot256' respectively.
```{r}
setwd("C:/Users/Stefan/Desktop/New_Simulations")
library(PhyloSim)

outfolder100 = "plots100"
dir.create(paste("./",outfolder100, sep = ""))

outfolder256 = "plots256"
dir.create(paste("./",outfolder256, sep = ""))
```

8. Null Models
-------------------------
First the Phylogenetic Dispersion is plotted for the last time step. As the setup is the same in both cases we only have to define the positions once.

```{r}
setwd("C:/Users/Stefan/Desktop/New_Simulations")
load("nullmeta100x100.RData")
load("nullmeta256x256.RData")


positions <- list(x= c(1:7),
    y = c(4, 1:3), # this is beacause dispersal = "global" is equal to dispersal = "0"
    zname = c("neutral", "1", "0.75", "0.5", "0.25", "0", "both"), # = environment
    yname = c("global", "0.5", "2", "4"),  # = dispersal
    xname=c("neutral", "0", "0.25", "0.5","0.75","1","both")) # = density
 
```

Now we can plot the results and save the plots as a pdf file.
```{r}
 plotPhylogeneticDispersion(pvalues = nullMeta100, positions = positions,  title = "Null Meta")

  name <- paste("./",outfolder100, "/PhylogeneticDisersion", 100, ".pdf", sep = "")
  dev.copy(pdf,name, width=9, height=6)
  dev.off()

  
 plotPhylogeneticDispersion(pvalues = nullMeta256, positions = positions,  title = "Null Meta")

  name <- paste("./",outfolder256, "/PhylogeneticDisersion", 256, ".pdf", sep = "")
  dev.copy(pdf,name, width=9, height=6)
  dev.off()



```


Now all the mean values of all recorded time steps are shown in the plots. This can give information about the robustness of the results.

```{r}
par(mfrow=c(4,7), mar=c(0.5, 0.5, 0.5, 0.5))

colfunc <- colorRampPalette(c("blue", "red"))
cols<-colfunc(10)  
  
pvalues<-nullMeta100
pval<-pvalues[[1]]
lengths = as.numeric(names(pval[[1]]))
nlengths = length(lengths)

Pmean<-matrix(NA,length(pvalues), length(as.numeric(names(pvalues[[1]][[1]]))))
z <- array(NA, dim=c(nlengths,length(pval), length(pvalues)))


## Build  plot
for(t in 1:length(pvalues)){
pval<-pvalues[[t]]
lengths = as.numeric(names(pval[[1]]))
nlengths = length(lengths)

for (i in 1:length(pval)){
  z[,i,t] <- sapply(pval[[i]], mean, na.rm = T)
}
}

for(i in 1:28){
  t<-1
plot(1:9,z[,i,t], type="l", xlim=c(1,9), ylim=c(0, 0.8), col=cols[t], yaxt="n", xaxt="n")
  for(t in 2:length(pvalues)){
  lines(1:9,z[,i,t], col=cols[t])
  }
}  


  name <- paste("./",outfolder100, "/PhylogeneticDisersion_allRuns", 100, ".pdf", sep = "")
  dev.copy(pdf,name, width=9, height=6)
  dev.off()


#### Same for nullMeta256
pvalues<-nullMeta256
pval<-pvalues[[1]]
lengths = as.numeric(names(pval[[1]]))
nlengths = length(lengths)

Pmean<-matrix(NA,length(pvalues), length(as.numeric(names(pvalues[[1]][[1]]))))
z <- array(NA, dim=c(nlengths,length(pval), length(pvalues)))


## Build  plot
for(t in 1:length(pvalues)){
pval<-pvalues[[t]]
lengths = as.numeric(names(pval[[1]]))
nlengths = length(lengths)

for (i in 1:length(pval)){
  z[,i,t] <- sapply(pval[[i]], mean, na.rm = T)
}
}

for(i in 1:28){
  t<-1
plot(1:9,z[,i,t], type="l", xlim=c(1,9), ylim=c(0, 0.8), col=cols[t], yaxt="n", xaxt="n")
  for(t in 2:length(pvalues)){
  lines(1:9,z[,i,t], col=cols[t])
  }
}  

name <- paste("./",outfolder256, "/PhylogeneticDisersion_allRuns", 256, ".pdf", sep = "")
  dev.copy(pdf,name, width=9, height=6)
  dev.off()
  
```


9. Species Richness
------------------------------
```{r}
setwd("C:/Users/Stefan/Desktop/New_Simulations")
load("SpecRich100x100.RData")
load("SpecRich256x256.RData")

.pardefault <- par(no.readonly = T) 

par(mfrow=c(4,7), mar=c(0.5, 0.5, 0.5, 0.5) )
for(i in 1:28){
  plot(seq(50000,100000,len=10), SpeciesRichness100[i,], type="l", 
       xlab="", ylim=c(min(SpeciesRichness100),max(SpeciesRichness100)), 
       ylab="", yaxt='n', xaxt='n', lwd=2, col="blue")
  abline(h=mean(SpeciesRichness100[i,]), lty=2, col=rgb(0,0,1,0.5))
  if(mean(SpeciesRichness100[i,])> max((SpeciesRichness100)+min(SpeciesRichness100))/2){
    ypos<-quantile(SpeciesRichness100, 0.25)
  }else{
     ypos<-quantile(SpeciesRichness100,0.95)
    }
  text(x=70000, y= ypos, labels=paste("m = ",mean(SpeciesRichness100[i,])),cex=0.9)
  
}

  name <- paste("./",outfolder100, "/SpeciesRichness", 100, ".pdf", sep = "")
  dev.copy(pdf,name, width=9, height=6)
  dev.off()
  
for(i in 1:28){
  plot(seq(50000,100000,len=10), SpeciesRichness256[i,], type="l", 
       xlab="", ylim=c(min(SpeciesRichness256),max(SpeciesRichness256)), 
       ylab="", yaxt='n', xaxt='n')
  abline(h=mean(SpeciesRichness256[i,]), lty=2, col=rgb(0,0,1,0.5))
  if(mean(SpeciesRichness100[i,])> max((SpeciesRichness256)+min(SpeciesRichness256))/2){
    ypos<-quantile(SpeciesRichness256, 0.25)
  }else{
     ypos<-quantile(SpeciesRichness256,0.95)
    }
  text(x=60000, y= ypos, labels=paste("mean = ",mean(SpeciesRichness256[i,])))
  
}

  name <- paste("./",outfolder256, "/SpeciesRichness", 256, ".pdf", sep = "")
  dev.copy(pdf,name, width=9, height=6)
  dev.off()

par(.pardefault)  
```

10. Gamma Statistics
------------------------------------
```{r}
setwd("C:/Users/Stefan/Desktop/New_Simulations")
load("GammaStat100.RData")
load("GammaStat256.RData")

par(mfrow=c(4,7), mar=c(0.5, 0.5, 0.5, 0.5) )
for(i in 1:28){
  plot(seq(50000,100000,len=10), gammas100[i,], type="l", 
       xlab="", ylim=c(min(gammas100),max(gammas100)), 
       ylab="", yaxt='n', xaxt='n')
  abline(h=mean(gammas100[i,]), lty=2)
}
  
  name <- paste("./",outfolder100, "/GammaStats", 100, ".pdf", sep = "")
  dev.copy(pdf,name, width=9, height=6)
  dev.off()
  
for(i in 1:28){
  plot(seq(50000,100000,len=10), gammas256[i,], type="l", 
       xlab="", ylim=c(min(gammas256),max(gammas256)), 
       ylab="", yaxt='n', xaxt='n')
    abline(h=mean(gammas256[i,]), lty=2)
}

  name <- paste("./",outfolder256, "/GammaStats", 256, ".pdf", sep = "")
  dev.copy(pdf,name, width=9, height=6)
  dev.off()

par(.pardefault)
```


11. Colless' Imbalance
-------------------------------
```{r}
setwd("C:/Users/Stefan/Desktop/New_Simulations")
load("Colless100.RData")
load("Colless256.RData")

par(mfrow=c(4,7), mar=c(0.5, 0.5, 0.5, 0.5) )
for(i in 1:28){
  plot(seq(50000,100000,len=10), colless100[i,], type="b", 
       xlab="", ylim=c(min(colless100, na.rm=T),max(colless100, na.rm=T)), 
       ylab="", yaxt='n', xaxt='n')
  abline(h=mean(colless100[i,], na.rm=TRUE), lty=2)
}

  name <- paste("./",outfolder100, "/Colless", 100, ".pdf", sep = "")
  dev.copy(pdf,name, width=9, height=6)
  dev.off()

  for(i in 1:28){
  plot(seq(50000,100000,len=10), colless256[i,], type="b", 
       xlab="", ylim=c(min(colless256, na.rm=T),max(colless256, na.rm=T)), 
       ylab="", yaxt='n', xaxt='n')
}

  name <- paste("./",outfolder256, "/Colless", 256, ".pdf", sep = "")
  dev.copy(pdf,name, width=9, height=6)
  dev.off()

  par(.pardefault)
```



12. SAC
--------------------------------

```{r}
setwd("C:/Users/Stefan/Desktop/New_Simulations")
load("results100x100.RData")
load("results256x256.RData")

par(mfrow=c(1,2))

for(i in 1:28){
  title <- paste("100x100", "Simulation", i)
sac(simulationOut100[[i]], which.result = NULL, title= title)
sac(simulationOut100[[i]], which.result = "all", title= title)  
  
  name <- paste("./",outfolder100, "/SAC100_Scenario_", i, ".pdf", sep = "")
  dev.copy(pdf,name, width=9, height=6)
  dev.off()

  title <- paste("256x256", "Simulation", i)  
sac(simulationOut256[[i]], which.result = NULL, title=title)
sac(simulationOut256[[i]], which.result = "all", title=  title)  
  
  name <- paste("./",outfolder256, "/SAC256_", i, ".pdf", sep = "")
  dev.copy(pdf,name, width=9, height=6)
  dev.off()
  
}

```

13. RAC
------------------------------------

```{r}
setwd("C:/Users/Stefan/Desktop/New_Simulations")
load("results100x100.RData")
load("results256x256.RData")

par(mfrow=c(1,2))

for(i in 1:28){
    title <- paste("100x100", "Simulation", i)
rac(simulationOut100[[i]], which.result = NULL, title=title)
rac(simulationOut100[[i]], which.result = "all", title= title)  
  
  name <- paste("./",outfolder100, "/RAC100_Scenario_", i, ".pdf", sep = "")
  dev.copy(pdf,name, width=9, height=6)
  dev.off()
  
  title <- paste("256x256", "Simulation", i)
rac(simulationOut256[[i]], which.result = NULL, title=title)
rac(simulationOut256[[i]], which.result = "all", title= title)  
  
  name <- paste("./",outfolder256, "/RAC256_", i, ".pdf", sep = "")
  dev.copy(pdf,name, width=9, height=6)
  dev.off()
  
}

```





  