// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP PhylGeo_rcpp_hello_world() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        List __result = rcpp_hello_world();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// RcppModel
NumericMatrix RcppModel(int dim, int specRate, int runs);
RcppExport SEXP PhylGeo_RcppModel(SEXP dimSEXP, SEXP specRateSEXP, SEXP runsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type dim(dimSEXP );
        Rcpp::traits::input_parameter< int >::type specRate(specRateSEXP );
        Rcpp::traits::input_parameter< int >::type runs(runsSEXP );
        NumericMatrix __result = RcppModel(dim, specRate, runs);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
