---
title: "indexAnalysis"
output: 
  html_document:
    keep_md: true
---

```{r packages_and_data}
require(PhylGeo)
require(picante)


  fileName <- "globalNeutral"
  file <- paste("C:/Users/Paul/Desktop/Data/",fileName, ".rdata", collapse="", sep="")
  load(file)
```

```{r ses_indices}

  plotSize <- (c(2,3,4,5,6,7,8,9,10,20,30,40))^2
  numberOfPlots <- floor(256^2/plotSize)
  nullModels <- sort(c("taxa.labels", "richness", "frequency", "sample.pool", "phylogeny.pool", "independentswap", "trialswap"))
  
   mat <- matrix(OUT$specOut, ncol=256, nrow=256)
   phylo <- read.tree(text = OUT$phyloOut)
   extantPhylo <- drop.fossil(phylo)
   extantPhyloCophen <- cophenetic(extantPhylo)
  
  sesMNTD <- list()
  sesMPD <- list()
  k = 1
  for(j in 1:length(nullModels)){
  for(i in 1:length(numberOfPlots))
  {
    comMat <- localPlots(size = plotSize[i], n = numberOfPlots[i], matrix = mat, community = T)$communityTable
    sesMNTD[[k]] <- ses.mntd(samp = comMat, dis = extantPhyloCophen, null.model = nullModels[j],runs=999, iterations=1000)  
    sesMPD[[k]] <- ses.mpd(samp = comMat, dis = extantPhyloCophen, null.model = nullModels[j] ,runs=999, iterations=1000)
    k = k+1
  }
  }
  testNames <- paste(sort(rep(nullModels, length(numberOfPlots))),"_", plotSize, "_", numberOfPlots, sep="")
  
```

```{r test_metrics}
  meanPvaluesMNTD <- numeric()
  meanPvaluesMPD <- numeric()
  pValueListMNTD <- list()
  pValueListMPD <- list()
  
 for(i in 1:length(sesMNTD))
 { 
   meanPvaluesMNTD[i] <-mean(sesMNTD[[i]]$mntd.obs.p)
   pValueListMNTD[[i]] <- sesMNTD[[i]]$mntd.obs.p
 }
  
 for(i in 1:length(sesMPD))
 { 
   meanPvaluesMPD[i] <-mean(sesMPD[[i]]$mpd.obs.p)
   pValueListMPD[[i]] <- sesMPD[[i]]$mpd.obs.p
 }

  names(pValueListMPD) <- names(pValueListMNTD) <- testNames
     
     
  
```

```{r plots, fig.width = 10, fig.height = 8}
  gCols <- gray.colors(length(sesMPD))
  Cols <- rainbow(length(sesMPD))
  hist(meanPvaluesMNTD, main = "MNTD", col = gCols)
  hist(meanPvaluesMPD, main = "MPD", col = gCols)
  
  boxplot(pValueListMNTD, ylim = c(-0.1, 1.1), col = Cols, border = "grey30", main = "MNTD", las=2)
  boxplot(pValueListMPD, ylim = c(-0.1, 1.1), col = Cols, border = "grey30", main = "MPD", las=2)
  
```

