---
title: "Mortality"
output: 
  html_document:
    keep_md: true
---

```{r packages, echo=FALSE}
require(picante)
require(PhylGeo)
```

###Dispersal Limitation + Environment
####Mortality
```{r mortality, echo=FALSE, fig.width=20, fig.height=10}
tr <- fullMod(x = 50, y = 50, dispersal = 3, runs = 10000, specRate = 2.0, density = F, environment = F, mortalityFitness = T, mortalityStrength = 20, reproductiveFitness = F, neutral = F, dispersalCut = 2, densityCut = 1, seed = 1000, saveLocation = "C:/Users/Paul/Desktop/Data/backupLocal")

phylogenyEx <- drop.fossil(tr$phylogeny)

plotSpatialPhylo(tr$specMat, phylogenyEx, plot = "both")
image(tr$traitMat)
rac(tr$specMat, plot = T)

ptrVal <- nullModelSample(speciesMatrix = tr$specMat, phylogeny = phylogenyEx, localPlotSize = 25, numberOfPlots = 50, repetitions = 10000)

boxplot(ptrVal,main="sample")

ptrVal <- nullModel(speciesMatrix = tr$specMat, phylogeny = phylogenyEx, localPlotSize = 25, numberOfPlots = 50, repetitions = 10000)

boxplot(ptrVal, main = "metacommunity")
```

####Reproduction
```{r reproduction, echo=FALSE, , fig.width=20, fig.height=10}
tr <- fullMod(x = 50, y = 50, dispersal = 3, runs = 5000, specRate = 2.0, density = F, environment = T, mortalityFitness = F, reproductiveFitness = T, neutral = F, dispersalCut = 2, densityCut = 4, seed = 100)

phylogenyEx <- drop.fossil(tr$phylogeny)

plotSpatialPhylo(tr$specMat, phylogenyEx, plot = "both")

rac(tr$specMat, plot = T)

ptrVal <- nullModelSample(speciesMatrix = tr$specMat, phylogeny = phylogenyEx, localPlotSize = 25, numberOfPlots = 50, repetitions = 10000)

boxplot(ptrVal,main="sample")

ptrVal <- nullModel(speciesMatrix = tr$specMat, phylogeny = phylogenyEx, localPlotSize = 25, numberOfPlots = 50, repetitions = 10000)

boxplot(ptrVal, main = "metacommunity")
```

####Mortality and Reproduction
```{r mortality_and_reproduction, echo=FALSE, fig.width=20, fig.height=10}
tr <- fullMod(x = 50, y = 50, dispersal = 3, runs = 5000, specRate = 2.0, density = F, environment = T, mortalityFitness = T, reproductiveFitness = T, neutral = F, dispersalCut = 2, densityCut = 4, seed = 100)

phylogenyEx <- drop.fossil(tr$phylogeny)

plotSpatialPhylo(tr$specMat, phylogenyEx, plot = "both")

rac(tr$specMat, plot = T)

ptrVal <- nullModelSample(speciesMatrix = tr$specMat, phylogeny = phylogenyEx, localPlotSize = 25, numberOfPlots = 50, repetitions = 10000)

boxplot(ptrVal,main="sample")

ptrVal <- nullModel(speciesMatrix = tr$specMat, phylogeny = phylogenyEx, localPlotSize = 25, numberOfPlots = 50, repetitions = 10000)

boxplot(ptrVal, main = "metacommunity")
```

###No Dispersal Limitation
####Mortality
```{r mortality_global, echo=FALSE, fig.width=20, fig.height=10}
tr <- fullMod(x = 50, y = 50, dispersal = 1, runs = 10000, specRate = 2.0, density = F, environment = T, mortalityFitness = T, mortalityStrength = 20, reproductiveFitness = F, neutral = F, dispersalCut = 2, densityCut = 4, seed = 100, saveLocation = "C:/Users/Paul/Desktop/Data/backupGlobal")

phylogenyEx <- drop.fossil(tr$phylogeny)

plotSpatialPhylo(tr$specMat, phylogenyEx, plot = "both")

rac(tr$specMat, plot = T)

ptrVal <- nullModelSample(speciesMatrix = tr$specMat, phylogeny = phylogenyEx, localPlotSize = 25, numberOfPlots = 50, repetitions = 10000)

boxplot(ptrVal,main="sample")

ptrVal <- nullModel(speciesMatrix = tr$specMat, phylogeny = phylogenyEx, localPlotSize = 25, numberOfPlots = 50, repetitions = 10000)

boxplot(ptrVal, main = "metacommunity")
```

####Reproduction
```{r reproduction_global, echo=FALSE, fig.width=20, fig.height=10}
tr <- fullMod(x = 50, y = 50, dispersal = 1, runs = 5000, specRate = 2.0, density = F, environment = T, mortalityFitness = F, reproductiveFitness = T, neutral = F, dispersalCut = 2, densityCut = 4, seed = 100)

phylogenyEx <- drop.fossil(tr$phylogeny)

plotSpatialPhylo(tr$specMat, phylogenyEx, plot = "both")

rac(tr$specMat, plot = T)

ptrVal <- nullModelSample(speciesMatrix = tr$specMat, phylogeny = phylogenyEx, localPlotSize = 25, numberOfPlots = 50, repetitions = 10000)

boxplot(ptrVal,main="sample")

ptrVal <- nullModel(speciesMatrix = tr$specMat, phylogeny = phylogenyEx, localPlotSize = 25, numberOfPlots = 50, repetitions = 10000)

boxplot(ptrVal, main = "metacommunity")
```

####Mortality and Reproduction
```{r mortality_and_reproduction_global, echo=FALSE, fig.width=20, fig.height=10}
tr <- fullMod(x = 50, y = 50, dispersal = 1, runs = 5000, specRate = 2.0, density = F, environment = T, mortalityFitness = T, reproductiveFitness = T, neutral = F, dispersalCut = 2, densityCut = 4, seed = 100)

phylogenyEx <- drop.fossil(tr$phylogeny)

plotSpatialPhylo(tr$specMat, phylogenyEx, plot = "both")

rac(tr$specMat, plot = T)

ptrVal <- nullModelSample(speciesMatrix = tr$specMat, phylogeny = phylogenyEx, localPlotSize = 25, numberOfPlots = 50, repetitions = 10000)

boxplot(ptrVal,main="sample")

ptrVal <- nullModel(speciesMatrix = tr$specMat, phylogeny = phylogenyEx, localPlotSize = 25, numberOfPlots = 50, repetitions = 10000)

boxplot(ptrVal, main = "metacommunity")
```