---
title: "nullModelCheck"
output: 
  html_document:
    keep_md: true
---

```{r pakcages_and_data}
require(picante)
require(PhylGeo)
require(shape)
require(fields)

files = c("globalEnv", "globalNeutral", "globalDensNN", "globalBothNN","local8Env", "local8Neutral", "local8DensNN", "local8BothNN", "local4Env", "local4Neutral", "local4DensNN", "local4BothNN","local8BothWide","local8DensWide", "local4BothWide","local4DensWide")

outList <- list()
for(i in 1:length(files)){
  file <- paste("C:/Users/Paul/Desktop/Data/",files[i], ".rdata", collapse="", sep="")
  load(file)
  outList[[i]] <- OUT
   
}
names(outList) <- files
rm(file, files, i, OUT)
```

```{r calculating_pvalues}
pvals <- list()
for(i in 1:length(outList)){
  s <- matrix(outList[[i]]$specOut, nrow = 256, ncol = 256)
  phyl <- read.tree(text = outList[[i]]$phyloOut)
  extantPhylo <- drop.fossil(phy = phyl)
  pvals[[i]] <- nullModel(speciesMatrix = s, localPlotSize = 100, phylogeny = extantPhylo, numberOfPlots = 650,repetitions = 1000)
}

names(pvals) <- names(outList)

pvalsRecon <- list()
for(i in 1:length(outList)){
  s <- matrix(outList[[i]]$specOut, nrow = 256, ncol = 256)
  t <- matrix(outList[[i]]$neutralOut, nrow = 256, ncol = 256)
  extantPhylo <- phyloReconstruct(speciesMatrix = s, traitMatrix = t, "ward.D2")
  pvalsRecon[[i]] <- nullModel(speciesMatrix = s, localPlotSize = 100, phylogeny = extantPhylo, numberOfPlots = 650,repetitions = 1000)
}
names(pvalsRecon) <- names(outList)
```

### Plots Recorded Phylogeny
```{r plotting_recorded_phylogeny_and_landscape, fig.width=20, fig.height= 10, echo=FALSE}
par(oma = c(0, 0, 2, 0))
for(i in 1:length(outList)){
  s <- matrix(outList[[i]]$specOut, nrow = 256, ncol = 256)
  phyl <- read.tree(text = outList[[i]]$phyloOut)
  extantPhylo <- drop.fossil(phy = phyl)
  plotSpatialPhylo(landscape = s, phylogeny = extantPhylo, plot = "both")
  mtext(names(outList)[i], outer = TRUE, cex = 1.5)
  
}
```

### Plots Reconstructed Phylogeny
```{r plotting_reconstructed_phylogeny_and_landscape, fig.width=20, fig.height= 10}
par(oma = c(0, 0, 2, 0))
for(i in 1:length(outList)){
  s <- matrix(outList[[i]]$specOut, nrow = 256, ncol = 256)
  t <- matrix(outList[[i]]$neutralOut, nrow = 256, ncol = 256)
  extantPhylo <- phyloReconstruct(speciesMatrix = s, traitMatrix = t, "ward.D")
  plotSpatialPhylo(landscape = s, phylogeny = extantPhylo, plot = "both")
  mtext(names(outList)[i], outer = TRUE, cex = 1.5)
  
}

```

### P-Value Boxplots
```{r plotting_pValues_in_boxplots, fig.width=20, fig.height= 10, echo=FALSE}
par(oma = c(4.5, 0, 0, 0))
a <- boxplot(pvals, las=2, ylim=c(0,1.1), main="p-Values MPD, recorded")
text(x = seq(1,16,1), labels = round(sapply(pvals, mean),2), y = 1.1)

a <- boxplot(pvalsRecon, las=2, ylim=c(0,1.1), main="p-Values MPD, reconstructed")
text(x = seq(1,16,1), labels = round(sapply(pvalsRecon, mean),2), y = 1.1)
par(oma = c(0, 0, 0, 0))
```

### Spatial Patterns
```{r plotting_spatial_patterns, fig.width=15, fig.height= 10, echo=FALSE}
par(mar=c(4.1, 4.1, 4.1, 9.1), xpd=TRUE)
topcol <- rainbow(16)
a <- numeric()
for(i in 1:length(outList)){
  s <- matrix(outList[[i]]$specOut, nrow = 256, ncol = 256)
  a[i] <- length(table(s))
}
barplot(a, col = topcol, ylab = "Species Richness", main = "Species Richness", xlab="Scenarios")
legend(legend= names(outList),inset=c(-0.25,1),"right",  fill = topcol, bty = "n")


s <- matrix(outList[[1]]$specOut, nrow = 256, ncol = 256)
plot(rac(s, plot=F), xlim=c(0,50), log="y", type="l", col=topcol[1], main = "Rank-Abundance Curves", lwd = 2, ylim=c(1,70000), ylab = "Abundance", xlab="Rank")
for(i in 2:length(outList)){
  s <- matrix(outList[[i]]$specOut, nrow = 256, ncol = 256)
  lines(rac(s, plot = F), col=topcol[i], lwd = 2)
}
legend(legend= names(outList),inset=c(-0.25,1),"right",  fill = topcol, bty = "n")

# plotting the species-area curves
s <- matrix(outList[[1]]$specOut, nrow = 256, ncol = 256)
sa <- sac(area = c(1,10,100,1000,10000,50000), rep = 100, matrix = s, plot=F)
plot(sa$area,sa$sr.Mean, xlim=c(1,50000), log="xy", type="l", col=topcol[1],ylim=c(1,50), main = "Species-Area Curves", lwd = 2, xlab="Area", ylab="Species Richness")
for(i in 2:length(outList)){
  s <- matrix(outList[[i]]$specOut, nrow = 256, ncol = 256)
  sa <- sac(area = c(1,10,100,1000,10000,50000), rep = 100, matrix = s, plot=F)
  lines(sa$area,sa$sr.Mean, col=topcol[i], lwd = 2)
}
legend(legend= names(outList),inset=c(-0.25,1),"right",  fill = topcol, bty = "n")
```

```{r pValue_matrix, echo = FALSE}

pvals <- pvals[c(1:4,5:8,13:14,9:12,15:16)]

for(i in 1:length(pvals)){
z[i] <- median(pvals[[i]], na.rm = T)
zSD[i] <- sd(pvals[[i]], na.rm = T)
}

y <- 0.9
j <- 1
xlables <- c("Env", "Neutral", "Dens", "Both", "Both\n(Wide)", "Dens\n(Wide)")
ylables <- c("global", "local8", "local4")
ColPalet <- colorRampPalette(c("blue", "white", "red"))
Cols <- ColPalet(100)
index <- seq(0,1,0.01)
# Cols[which.max(index[index <= z[5]])]
 par(mar=c(0, 2, 0, 0), xpd=TRUE)
emptyplot(xlim=c(-1.5, 1.5), ylim=c(0.4,1.15), frame.plot = F)
title("p-Values", line=-5)
 
  for(k in 1:3){#
    x <--1.0
    if(k==1) a=4
    else a = 6
    for(i in 1:a){
      filledrectangle(wx = 0.2, wy = 0.2, col = Cols[which.max(index[index <= z[j]])], mid = c(x, y), angle = 0)
      text(x = x, y = y+0.05, labels = round(z[j],digits = 3))
      text(x = x, y = y-0.05, labels = round(zSD[j],digits = 3))
      if(k==3) text(x = x, y = 1.1, labels = xlables[i])
      x <- x + 0.25
      j <- j+1
#       print(j)
    }
  text(x = -1.4, y = y, labels = ylables[k])  
  text(x = -1.2, y = y+0.05, labels = "Median", cex = 0.8)  
  text(x = -1.2, y = y-0.05, labels = "SD",  cex = 0.8)  
  y <- y - 0.25
}
colorbar.plot(x = 0.7, y = 0.7, strip=seq(0,1,0.001), col=Cols, strip.length = 0.3, horizontal = F, strip.width = 0.05)
text(x = 0.8, y = 1.1, labels = "overdispersed" , pos = 4) 
text(x = 0.8, y = 0.7, labels = "neutral" , pos = 4) 
text(x = 0.8, y = 0.3, labels = "underdispersed \n(clustered)", pos = 4) 

```

