---
title: "scenarioCheck"
output: 
  html_document:
    keep_md: true
---

This is the analysis of 100 simulation runs. 
These runs where conducted with a grid size of 50 by 50 cells. 
Each simulation was run over 100k generations with the same settings. 
The only thing different in each run was the random seed. 
This analysis is designed to assess the variation between simulation runs and to determine whether the model reaches equilibrium. 

```{r packages_and_data}
require(PhylGeo)
require(shape)
require(fields)
require(vegan)
require(ape)
require(picante)


files = c("globalEnv", "globalNeutral", "globalDensNN", "globalBothNN","local8Env", "local8Neutral", "local8DensNN", "local8BothNN", "local4Env", "local4Neutral", "local4DensNN", "local4BothNN","local8BothWide","local8DensWide", "local4BothWide","local4DensWide")

outList <- list()
for(i in 1:length(files)){
  file <- paste("C:/Users/Paul/Desktop/Data/",files[i], ".rdata", collapse="", sep="")
  load(file)
  outList[[i]] <- OUT
   
}
names(outList) <- files
rm(file, files, i, OUT)
``` 

```{r calculating_pvalues, echo=FALSE}

pvals <- list()
for(i in 1:length(outList)){
  print(i)
  s <- matrix(outList[[i]]$specOut, nrow = 256, ncol = 256)
  phyl <- read.tree(text = outList[[i]]$phyloOut)
  extantPhylo <- drop.fossil(phy = phyl)
  phy.exta <- cophenetic(extantPhylo)
  comMat <- localPlots(100,650,matrix = s, community = T)$communityTable
  # SES.mntd.phylogeny.pool <- ses.mntd(comMat, phy.exta, "phylogeny.pool",runs=999, iterations=1000)  #4
  SES.mntd.phylogeny.pool <- ses.mntd(comMat, phy.exta, "richness",runs=999, iterations=1000)  #4
  pvals[[i]] <- SES.mntd.phylogeny.pool
}

names(pvals) <- names(outList)



pvalsRecon <- list()
for(i in 1:length(outList)){
  print(i)
  s <- matrix(outList[[i]]$specOut, nrow = 256, ncol = 256)
  t <- matrix(outList[[i]]$neutralOut, nrow = 256, ncol = 256)
  extantPhylo <- phyloReconstruct(speciesMatrix = s, traitMatrix = t, "ward.D")
  phy.exta <- cophenetic(extantPhylo)
  comMat <- localPlots(100,650,matrix = s, community = T)$communityTable
  SES.mntd.phylogeny.pool <- ses.mntd(comMat, phy.exta, "richness",runs=999, iterations=1000)  #4
  pvalsRecon[[i]] <- SES.mntd.phylogeny.pool
}
names(pvalsRecon) <- names(outList)

```

```{r plotting_the_ses, echo=F}

z <- numeric()
zSD <- numeric()
pValueTable <- data.frame(x = rep(NA, 650))
reconPValueTable <- data.frame(x = rep(NA, 650))

for(i in 1:length(pvals)){
z[i] <- mean(pvals[[i]]$mpd.obs.p, na.rm = T)
zSD[i] <- sd(pvals[[i]]$mpd.obs.p, na.rm = T)

pValueTable <- cbind(pValueTable, pvals[[i]]$mntd.obs.p)
reconPValueTable <- cbind(reconPValueTable, pvalsRecon[[i]]$mntd.obs.p)
}

pValueTable <- pValueTable[,-1]

reconPValueTable <- reconPValueTable[,-1]

colnames(pValueTable) <- names(outList)
colnames(reconPValueTable) <- names(outList)
Cols <- rainbow(16)
par(mar=c(7.1, 3.1, 2.1, 2.1), xpd=TRUE, mfrow=c(2,1))
boxplot(pValueTable, ylim = c(-0.1, 1.1), col = Cols, border = "grey30", main = "recorded phylogeny", las=2)
abline(h = 0.5)
boxplot(reconPValueTable, ylim = c(-0.1, 1.1), col = Cols, border = "grey30", main = "reconstructed phylogeny", las=2)
abline(h = 0.5)
par(mfrow=c(1,1))

```