#' @title Plot Phylogenetix Dispersion
#' @description Plotting function for the results of \code{\link{calculatePhylogeneticDispersion}}. Usefull for plotting different scenarios.
#' @param pvalues List of p-values as generated by \code{\link{calculatePhylogeneticDispersion}}.
#' @param positions List, determines where the plots should be placed and how they should be labeled
#' @param title String, determines the title of the plot
#' @param multiple
#' @return A plot
#' @examples 
#' ## Define a parameterset. Note that the setup here is duplicated in the
#' ## names in the positions argument.
#' runs = 2000
#' dispOptions = 4
#' fitOptions = 7
#'  
#' dispersal =  rep(c(0,0.5, 2,4), each = fitOptions)
#' density = rep(c(0,seq(0,1,len = fitOptions-2),1),dispOptions)
#' environment = rep(c(0,seq(1,0,len = fitOptions-2),1),dispOptions)
#' modes <- ifelse(dispersal == 0, "global", "local")
#' scenarios <- paste(modes, " dens=", density, " env=", environment, sep = "")
#' pars <- list()
#' for (i in 1:length(scenarios)){pars[[i]] = createCompletePar(x = 20,y = 20, runs = runs,scenario = scenarios[i], dispersal = dispersal[i],specRate = 2,density = density[i],environment = environment[i], fitnessBaseMortalityRatio = 5, densityCut = 1,seed = 1000)}
#' 
#' ## Run the simulations
#' simulationOut <- runSimulationBatch(pars, parallel = "auto")
#' 
#' ## Calculate null models
#' nullMeta <- calculatePhylogeneticDispersion(simulationOut, plotlengths = c(2,3,4,5,6,7,8,9,10), reduce = TRUE)
#' 
#' ## Define the positions where the plots should be drawn
#' positions <- list(x= c(1, seq(2.5,6.5,1), 8),
#'    y = c(4, 1:3),
#'    xname = c("neutral", "1", "0.75", "0.5", "0.25", "0", "both"),
#'    yname = c("global", "0.5", "2", "4" ))
#'
#' ## Plot the results
#' plotPhylogeneticDispersion(pvalues = nullMeta, positions = positions, title = "Null Meta", multiple = TRUE) 

#' @export

plotPhylogeneticDispersion <- function(pvalues, positions=NULL, title = "P-values", multiple = T){
  
  if (is.null(positions)){
    positions = list(x=1, y = 1, xname = "", yname = "")
  }  
  
  if(multiple == T){
    lengths = as.numeric(names(pvalues[[1]]))
    nlengths = length(lengths)
    lRange <- max(lengths) - min(lengths)
    
    z <- matrix(nrow = nlengths, ncol = length(pvalues), dimnames = list(names(pvalues[[1]]), names(pvalues)))
    zCILOW <- z
    zCIUP <- z
    for (i in 1:length(pvalues)){
      z[,i] <- sapply(pvalues[[i]], median, na.rm = T)
      zCILOW[,i] <- sapply(pvalues[[i]], function(x)quantile(x,0.25, na.rm = T))   
      zCIUP[,i] <- sapply(pvalues[[i]], function(x)quantile(x,0.75, na.rm = T))
    }
  }else{
    z <- sapply(pvalues, median, na.rm = T)
    zSD <- sapply(pvalues, sd, na.rm = T) 
  }
  
  
  
  ColPalet <- colorRampPalette(c("turquoise4", "white", "palevioletred"))
  Cols <- ColPalet(100)
  index <- seq(0,1,0.01)
  par(mar=c(0, 2, 0, 0), xpd=TRUE)
  shape::emptyplot(xlim=c(0, 5.5), ylim=c(0.5,2.5), frame.plot = FALSE)
  title(title, line=-2)
  
  
  
  for(i in 1:length(positions$y)){
    for(j in 1:length(positions$x)){
      
      x <- positions$x[j] / 2
      fitn = positions$xname[j]
      
      disp = positions$yname[i]
      y <- positions$y[i] / 2
      
      k <- 7*(i-1) + j
      
      if (multiple == T){
        
        mpv <- mean(z[,k])
        shape::filledrectangle(wx = 0.3, wy = 0.3, col = Cols[which.max(index[index <= mpv])], mid = c(x, y), angle = 0, lcol = "darkgrey")
        
        xval <- (lengths - min(lengths)) / lRange *0.3 -0.15
        yval <- z[,k] * 0.3 - 0.15
        yUP <- zCIUP[,k] * 0.3 - 0.15 
        yLOW <- zCILOW[,k] * 0.3 - 0.15
        
        polygon(c(x+xval, rev(x+xval)), c(y+yUP, rev(y+yLOW)), col = "#99999940", border = NA)
        lines(x+xval, y+yval)
        lines(c(x-0.15,x-0.13) , c(y , y ))
        lines(c(x+0.13,x+0.15) , c(y , y ))
        #lines(x+xval, y+ 0.5, lty=2)
        #lines(x+xval, y+yUP, lty = 2)
        #lines(x+xval, y+yLOW, lty = 2)
        
      }else{    
        shape::filledrectangle(wx = 0.3, wy = 0.3, col = Cols[which.max(index[index <= z[k]])], mid = c(x, y), angle = 0)
        text(x = x, y = y+0.05, labels = round(z[k],digits = 3))
        text(x = x, y = y-0.05, labels = round(zSD[k],digits = 3))        
      }
    }
  }
  
  text(x = 0, y = positions$y/2, labels = positions$yname , pos = 4) 
  text(x = positions$x/2, y = 2.3, labels =  positions$xname ) 
  
  barx <- 4.5
  bary <- 1.2
  barl <- 0.3
  fields::colorbar.plot(x = barx, y = bary, strip=seq(0,1,0.001), col=Cols, strip.length = barl, horizontal = F, strip.width = 0.04)
  text(x = barx + 0.2, y = bary + 1.8* barl, labels = "overdispersed" , pos = 4) 
  text(x = barx + 0.2, y = bary, labels = "neutral" , pos = 4) 
  text(x = barx + 0.2, y = bary - 1.8* barl, labels = "underdispersed \n(clustered)", pos = 4) 
}

