# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('PhylGeo_rcpp_hello_world', PACKAGE = 'PhylGeo')
}

#' @title Model of neutral community assembly
#' @description Runs a simple model of species community assembly under neutral conditions as defined by Hubbel. 
#' @param dim The edge-length of the square metacommunity matrix
#' @param specRate The speciation rate in total speciation events per generation
#' @param seed The random seed (do not change this option if you previously set the seed!)
#' @param runs The number of generations the model runs through
#' @details Be careful with the dimensions you choose. Large grids and many generations may take very long to compute. You can assume to have reached the equilibrium state of the model after dim^2/2.
RcppModel <- function(dim, specRate, runs) {
    .Call('PhylGeo_RcppModel', PACKAGE = 'PhylGeo', dim, specRate, runs)
}

