# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

callModel <- function(x, y, dispersal, runs, specRate, dens, env, mort, repro, neutral, dispersalCutoff, densityCutoff, seed, specOut, traitOut, neutralOut, compOut, envOut, phyloOut) {
    invisible(.Call('PhylGeo_callModel', PACKAGE = 'PhylGeo', x, y, dispersal, runs, specRate, dens, env, mort, repro, neutral, dispersalCutoff, densityCutoff, seed, specOut, traitOut, neutralOut, compOut, envOut, phyloOut))
}

